#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x0294A902A6830C07 (indigo@keybase.io)
#
Name     : pyflakes
Version  : 2.1.0
Release  : 53
URL      : https://files.pythonhosted.org/packages/48/6d/7bfd617b21292397e10e24af4cf42947a359b0c425b66f194cf5d14b1444/pyflakes-2.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/48/6d/7bfd617b21292397e10e24af4cf42947a359b0c425b66f194cf5d14b1444/pyflakes-2.1.0.tar.gz
Source99 : https://files.pythonhosted.org/packages/48/6d/7bfd617b21292397e10e24af4cf42947a359b0c425b66f194cf5d14b1444/pyflakes-2.1.0.tar.gz.asc
Summary  : passive checker of Python programs
Group    : Development/Tools
License  : MIT
Requires: pyflakes-bin = %{version}-%{release}
Requires: pyflakes-license = %{version}-%{release}
Requires: pyflakes-python = %{version}-%{release}
Requires: pyflakes-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils23
BuildRequires : buildreq-distutils3
BuildRequires : python-core
BuildRequires : setuptools-legacypython

%description
========
Pyflakes
========
A simple program which checks Python source files for errors.

%package bin
Summary: bin components for the pyflakes package.
Group: Binaries
Requires: pyflakes-license = %{version}-%{release}

%description bin
bin components for the pyflakes package.


%package legacypython
Summary: legacypython components for the pyflakes package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the pyflakes package.


%package license
Summary: license components for the pyflakes package.
Group: Default

%description license
license components for the pyflakes package.


%package python
Summary: python components for the pyflakes package.
Group: Default
Requires: pyflakes-python3 = %{version}-%{release}

%description python
python components for the pyflakes package.


%package python3
Summary: python3 components for the pyflakes package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyflakes package.


%prep
%setup -q -n pyflakes-2.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548340692
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export SOURCE_DATE_EPOCH=1548340692
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyflakes
cp LICENSE %{buildroot}/usr/share/package-licenses/pyflakes/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyflakes

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyflakes/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
